language: ruby
rvm:
- 2.4
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - secure: Qil7huI8ubrqeaRoARU4irOqFyhmTzmoYUxkPtZ8dIE+mZrm2xUpiAZtTD9WNy6bwGgoJ1mP+3PHDl53u1gyPSiUiMYJYEUBpKfqwPO16N7Uc98MPm0nvaF5mFkLZdYREtEVDKJB82ChUqqEasDoJZTrXqB1EnBOnxcHTVKhyhwusMSimbhfdcMao/M8eTlNl1vVvI3thMZzZjROirt063MqbpNjfa6hFlqMdBkIrBt10nr1wG/eldtvOx96+Sxt4tFVeJ1WO+LetOlk3ZbvAOA4xkaxEEMOWfI5EogxWv0EiKn26hlX+P+Bbvac5IWlB5rMqtRefOa9jfHYDPtL4fLErCg3BxI2kGTxp9mVy2I5t30Le3MUuL6ysK0Kyrbjj/nHJ3/Ct81flpf0tN8A5o4frCTa2xgkevc5A6FwCqi9PsTYD/41Lfl8nOkCbcWCmSQc3AoM7ww8NCqOt46Qj3Bg9JS8vl1lW0CFKrs/njC7nk5hnAw2XWO6/tOMvOsxxxM1ezRUqyVOcFCvsbcPUC/tdCoz86enW6alHmN1++putYahdleUVOX8XV5bvi3f+ReENfLGTXNuV4qOV3/8+x7EmpXpi3M81NsdamO4K80bmA0yDm7yDa5SVjcaN13jOsdG8jovvkN4bcrpbmEiHMPv4evp8OTcomXHLzi6pg0=
    - secure: dAFeI0lo2uZ/pfpPgez2Ef28BOBEcvKJjZCnIfbR+Uc7vEjf3Fahc6BAciy0kTdYJmqhrOf6eTIvc33S7SnmpF/kf8kOGgnmn6wO7NkY/N2FxUBtoR/QGH5GWQU6BR0k9BenhEXhQBfCpBqO2svkNJT9kZVU2R63hRXaPnM9mCcQovaOyPQiE9hMZmKhZlyHqDgiDdcLLA3jRV8IW2MwKow+GWzG3pyEUej0f6h9cPTQ4nUbXRg8u+i0daRLV6K5tqT6VDq1/4bbbPNBpXEVM5JzdgpOj/56UhHwDhhEeNL1o76AgO9gycjTYnL+1eeqhkuoCh9EpaYGS/BcSn/twAXdslzeuLTS9wpexj+48/xnStaroM/qPfTOB4b4aBAn4jkAjgXflh4SnfnW+T2C3dYLqzXeZ053KkGwQiY9gESP5eoTs/9wIqCDa0xW3OHGym7PP+iAwUogTdrcGqlHFmHT9hTw8xYUqsOHdRUrVa17hVUQJyCdw5+eALrJmyvUP12Kcup7muNsn1jkMX2xB8B7Q6mUjNTWxOcJKJKk/n/vFdPBoTmaJJ71TJvUaYPTM7/7wzELIeZI9NuuIO/WpsAAz9D64u3qtjgafrBiPd9HkRSeRwSoe1lhn8gmOBvN+hF397upM2pfl720PYyHNXI5ljdk1gwQ5SMXLhuLctc=
    - secure: Be2F4Dh3FOdMWnipveJAoIANkb0Rh6/u5JC4BtHyW38Bo4qzQEZhEksOptyGh/pwV73DwJhxm8KY6Qr46OCl2cTZczjsfwvZTQFP82S/8UYL0fCkbb5bQXNDoZDWGb+4fimnwlkdKPrpCH9kOO3t1jKAlQmiFHugA6gkmsyQ27eyMDLjJuGJQ1sMxedfIxB7k4Dc4vSe3lm6aza9KeOnGWcMi1sGJ255egHcPNE+2WLhUW4EYaSMstwEhk0iJ0Na7hZNtV9hWXB1VFwLBLfbFjey1Ag3FZ4veayApeYYBZ6vtSDF8Qp35jGgxhnhmIU3/dTqtFLGMsgIGT6aqIzzrsDVMoe1GkQH7xguhQt0/S7U4W9WNUdKFUwTiTJ6pWISWZlf9bsr5UVUsTPLRHn7EeoZgiDC5jy1RfiKwyfvspStbmZX5ptSOY2ve1Vnwh0IqSO0BRk67NoPAI7lCupa34kceHRRf7vT/w7tHJX3J80VfWE8NisiBFwL42Z/9WMJAUacRr3F33+qePj6IxcLU6bE0CbHMflbPf6MdVKx4/LJGI9F4a8JdqXYFQ/MPixTFc8VNz1+plNLZ6FNLym9AlQ8YX3ggeSLqUUXX/rWYanAGMtEVEkhcYRm3lTNRznBxmYps7S9ouuNsBhYutNqHy2VsUPgtL1OalOa21pgG8w=
branches:
  only:
    - master
script:
  - bundle exec jekyll build
  - bundle exec rake test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_470b63517309_key -iv $encrypted_470b63517309_iv
    -in deploy_blog_rsa.enc -out ~\/.ssh/deploy_blog_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy\_blog\_rsa
  - ssh-add /tmp/deploy\_blog\_rsa
  - echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after _site/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master